In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from power_plant_dataset import PowerPlantDataset

In [2]:
dataset = PowerPlantDataset(csv_file='fdcl/split/df_hdrm.csv')

In [3]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True, num_workers=4)

In [7]:
# 设置您想要打印的批次数量
num_batches_to_print = 3
# 使用enumerate遍历DataLoader
for batch_idx, (batch_features, batch_labels) in enumerate(dataloader):
    # 打印当前批次的数据
    print(f'Batch {batch_idx+1}: Features = {batch_features[:, 0].shape}, Labels = {batch_labels.shape}')
    print(batch_features)
    print(batch_features[:, 0])
    print(batch_labels)
    # 如果已经打印了足够的批次，则退出循环
    if batch_idx + 1 >= num_batches_to_print:
        break

Batch 1: Features = torch.Size([4]), Labels = torch.Size([4])
tensor([[1.0563e+04, 1.7009e+09],
        [8.9540e+03, 1.7008e+09],
        [8.4518e+03, 1.6996e+09],
        [1.0879e+04, 1.7008e+09]])
tensor([10563.0352,  8954.0107,  8451.7832, 10879.3057])
tensor([11.8705, 13.0029, 13.2389, 11.2894])
Batch 2: Features = torch.Size([4]), Labels = torch.Size([4])
tensor([[1.2820e+04, 1.7039e+09],
        [1.1840e+04, 1.6995e+09],
        [9.8705e+03, 1.7008e+09],
        [9.0975e+03, 1.7016e+09]])
tensor([12819.7314, 11840.2617,  9870.4863,  9097.5264])
tensor([11.3078, 10.6897, 12.2405, 13.0932])
Batch 3: Features = torch.Size([4]), Labels = torch.Size([4])
tensor([[1.2666e+04, 1.7031e+09],
        [1.1745e+04, 1.7028e+09],
        [1.1635e+04, 1.7034e+09],
        [8.1321e+03, 1.7004e+09]])
tensor([12666.4072, 11745.1250, 11635.2295,  8132.1172])
tensor([11.6736, 12.4232, 12.1585, 13.3966])
